#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package Net::Cassandra::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant VERSION => "19.4.0";

1;
